Back out "Prepare AWS for workload identity."
Was failing because IAM OIDC providers are singleton.

AM: CreateOpenIDConnectProvider, https response error StatusCode: 409, RequestID: 8e7afba2-89d0-4742-816e-63c3e7b5baea, EntityAlreadyExists: Provider with url https://token.actions.githubusercontent.com already exists.: provider=aws@6.68.0
     +  aws:iam:OpenIdConnectProvider monorepo_github_oidc_provider creating (0s) error: 1 error occurred:
     +  aws:iam:OpenIdConnectProvider monorepo_github_oidc_provider **creating failed** error: 1 error occurred:
    @ Updating.....
        pulumi:pulumi:Stack monorepo-2-prod running error: update failed
    @ Updating.....
        pulumi:pulumi:Stack monorepo-2-prod **failed** 1 error
     ~  ts:pulumi:zemn.me:hello_world monorepo_zemn.me_fargate_img updated [diff: ~token]
    Diagnostics:
      pulumi:pulumi:Stack (monorepo-2-prod):
        error: update failed

      aws:iam:OpenIdConnectProvider (monorepo_github_oidc_provider):
        error:   sdk-v2/provider2.go:515: sdk.helper_schema: creating IAM OIDC Provider: operation error IAM: CreateOpenIDConnectProvider, https response error StatusCode: 409, RequestID: 8e7afba2-89d0-4742-816e-63c3e7b5baea, EntityAlreadyExists: Provider with url https://token.actions.githubusercontent.com already exists.: provider=aws@6.68.0
        error: 1 error occurred:
        	* creating IAM OIDC Provider: operation error IAM: CreateOpenIDConnectProvider, https response error StatusCode: 409, RequestID: 8e7afba2-89d0-4742-816e-63c3e7b5baea, EntityAlreadyExists: Provider with url https://token.actions.githubusercontent.com already exists.

        [Pulumi Neo] Would you like help with these diagnostics?
        https://app.pulumi.com/Zemnmez/monorepo-2/prod/updates/15075?explainFailure

    Resources:
        ~ 2 updated
        49 unchanged
        2 errored

    Duration: 10s


Original commit changeset: 829a4100c0c5