Back out "fix(deps): update dependency twilio to v5.5.1"
Also prevents upgrading the twilio nodejs sdk. For reasons that are currently beyond me, it breaks on upgrade expecting to load the older version:

        pulumi:pulumi:Stack (monorepo-2-prod):
          Error: Cannot find module '.aspect_rules_js/twilio@5.4.5/node_modules/twilio/lib/index.js'
          Require stack:
          -
          -

Original commit changeset: cf67c14fe6be