Back out "See if I can make google analytics work (due to the nature of modifying csp, I'm testing this live)."
Original commit changeset: d9d6d1a756d8

Error: VM669:1 Uncaught ReferenceError: ga is not defined
    at <anonymous>:1:1