Remove swap storage disk space clear op. It looks like it was causing issues:
Run jlumbroso/free-disk-space@main
Run # ======
================================================================================
BEFORE CLEAN-UP:

$ dh -h /

Filesystem      Size  Used Avail Use% Mounted on
/dev/root        84G   62G   22G  74% /
$ dh -a /

Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root       87204404 64207120  22980900  74% /
$ dh -a

Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/root       87204404 64207120  22980900  74% /
devtmpfs         3544692        0   3544692   0% /dev
proc                   0        0         0    - /proc
sysfs                  0        0         0    - /sys
securityfs             0        0         0    - /sys/kernel/security
tmpfs            3549160      172   3548988   1% /dev/shm
devpts                 0        0         0    - /dev/pts
tmpfs            1419664     1092   1418572   1% /run
tmpfs               5120        0      5120   0% /run/lock
cgroup2                0        0         0    - /sys/fs/cgroup
pstore                 0        0         0    - /sys/fs/pstore
bpf                    0        0         0    - /sys/fs/bpf
systemd-1              -        -         -    - /proc/sys/fs/binfmt_misc
hugetlbfs              0        0         0    - /dev/hugepages
mqueue                 0        0         0    - /dev/mqueue
debugfs                0        0         0    - /sys/kernel/debug
tracefs                0        0         0    - /sys/kernel/tracing
fusectl                0        0         0    - /sys/fs/fuse/connections
configfs               0        0         0    - /sys/kernel/config
none                   0        0         0    - /run/credentials/systemd-sysusers.service
/dev/loop0         65024    65024         0 100% /snap/core20/1974
/dev/loop1        114688   114688         0 100% /snap/lxd/24322
/dev/loop2         54656    54656         0 100% /snap/snapd/19457
/dev/sdb15        106858     6182    100677   6% /boot/efi
binfmt_misc            0        0         0    - /proc/sys/fs/binfmt_misc
/dev/sda1       14341128  4194336   9396508  31% /mnt
tmpfs             709832       12    709820   1% /run/user/1001
tmpfs            1419664     1092   1418572   1% /run/snapd/ns
nsfs                   0        0         0    - /run/snapd/ns/lxd.mnt
================================================================================


********************************************************************************
=> Android library: Saved 12GiB
********************************************************************************


********************************************************************************
=> .NET runtime: Saved 1.7GiB
********************************************************************************


********************************************************************************
=> Haskell runtime: Saved 0B
********************************************************************************

Reading package lists...
Building dependency tree...
Reading state information...
Package 'dotnet-nightly' is not installed, so not removed
Package 'dotnet-targeting-pack-3.1' is not installed, so not removed
Package 'dotnet-host-7.0' is not installed, so not removed
Package 'dotnet-sdk-6.0-source-built-artifacts' is not installed, so not removed
Package 'dotnet-sdk-7.0-source-built-artifacts' is not installed, so not removed
Package 'dotnet-templates-6.0' is not installed, so not removed
Package 'dotnet-templates-7.0' is not installed, so not removed
Package 'dotnet-apphost-pack-3.1' is not installed, so not removed
Package 'dotnet-runtime-3.1' is not installed, so not removed
Package 'dotnet-sdk-3.1' is not installed, so not removed
Package 'dotnet-hostfxr-3.1' is not installed, so not removed
Package 'dotnet-runtime-deps-3.1' is not installed, so not removed
The following additional packages will be installed:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
The following packages will be REMOVED:
  aspnetcore-runtime-6.0 aspnetcore-runtime-7.0 dotnet-apphost-pack-6.0
  dotnet-apphost-pack-7.0 dotnet-host dotnet-hostfxr-6.0 dotnet-hostfxr-7.0
  dotnet-runtime-6.0 dotnet-runtime-7.0 dotnet-runtime-deps-6.0
  dotnet-runtime-deps-7.0 dotnet-sdk-6.0 dotnet-sdk-7.0
  dotnet-targeting-pack-6.0 dotnet-targeting-pack-7.0
The following packages will be upgraded:
  aspnetcore-targeting-pack-6.0 aspnetcore-targeting-pack-7.0
2 upgraded, 0 newly installed, 15 to remove and 17 not upgraded.
Need to get 3041 kB of archives.
After this operation, 990 MB disk space will be freed.
Ign:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.120-0ubuntu1~22.04.1
Ign:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.109-0ubuntu1~22.04.1
Err:1 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-6.0 amd64 6.0.120-0ubuntu1~22.04.1
  404  Not Found [IP: 52.252.75.106 80]
Err:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 aspnetcore-targeting-pack-7.0 amd64 7.0.109-0ubuntu1~22.04.1
  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet6/aspnetcore-targeting-pack-6.0_6.0.120-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/universe/d/dotnet7/aspnetcore-targeting-pack-7.0_7.0.109-0ubuntu1%7e22.04.1_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Error: Process completed with exit code 100.